import { AegisCareDatabaseSchema } from './schema';
import { hashPassword } from '../auth/tokens';

const defaultPasswordHash = hashPassword('demo123');

export const INITIAL_SEED_DATA: AegisCareDatabaseSchema = {
  users: [
    {
      id: 'usr-patient-1',
      email: 'rajesh.sharma@demo.aegiscare.in',
      passwordHash: defaultPasswordHash.hash,
      salt: defaultPasswordHash.salt,
      role: 'patient',
      name: 'Rajesh Sharma',
      title: 'Senior Citizen Patient',
      avatarInitials: 'RS',
      phone: '+91 98490 11223',
      associatedPatientId: 'pat-1',
      departmentOrAffiliation: 'Chronic Cardiac Care Group',
      isActive: true,
      createdAt: '2026-01-10T08:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
    {
      id: 'usr-family-1',
      email: 'sneha.sharma@demo.aegiscare.in',
      passwordHash: defaultPasswordHash.hash,
      salt: defaultPasswordHash.salt,
      role: 'family_member',
      name: 'Sneha Sharma',
      title: 'Primary Caregiver & Daughter',
      avatarInitials: 'SS',
      phone: '+91 98490 33445',
      associatedPatientId: 'pat-1',
      departmentOrAffiliation: 'Family Caregiver Circle',
      isActive: true,
      createdAt: '2026-01-10T08:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
    {
      id: 'usr-doctor-1',
      email: 'dr.ananya.rao@demo.aegiscare.in',
      passwordHash: defaultPasswordHash.hash,
      salt: defaultPasswordHash.salt,
      role: 'doctor',
      name: 'Dr. Ananya Rao, MD',
      title: 'Chief of Emergency Medicine',
      avatarInitials: 'AR',
      phone: '+91 98490 55667',
      associatedHospitalId: 'hosp-1',
      departmentOrAffiliation: 'Trauma & Emergency Care, Apollo Jubilee Hills',
      isActive: true,
      createdAt: '2026-01-10T08:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
    {
      id: 'usr-emt-1',
      email: 'vikram.singh@demo.aegiscare.in',
      passwordHash: defaultPasswordHash.hash,
      salt: defaultPasswordHash.salt,
      role: 'emt',
      name: 'Vikram Singh, EMT-P',
      title: 'Lead ALS Paramedic',
      avatarInitials: 'VS',
      phone: '+91 98490 77889',
      associatedAmbulanceId: 'amb-1',
      departmentOrAffiliation: 'Telangana 108 Emergency Medical Services',
      isActive: true,
      createdAt: '2026-01-10T08:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
    {
      id: 'usr-operator-1',
      email: 'dispatch.kavitha@demo.aegiscare.in',
      passwordHash: defaultPasswordHash.hash,
      salt: defaultPasswordHash.salt,
      role: 'ambulance_operator',
      name: 'Kavitha Reddy',
      title: 'Central EMS Dispatch Controller',
      avatarInitials: 'KR',
      phone: '+91 98490 99001',
      departmentOrAffiliation: 'Hyderabad Central EMS Command Depot',
      isActive: true,
      createdAt: '2026-01-10T08:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
    {
      id: 'usr-admin-hosp-1',
      email: 'admin.suresh@demo.aegiscare.in',
      passwordHash: defaultPasswordHash.hash,
      salt: defaultPasswordHash.salt,
      role: 'hospital_admin',
      name: 'Suresh Varma',
      title: 'Director of Hospital Operations',
      avatarInitials: 'SV',
      phone: '+91 98490 12345',
      associatedHospitalId: 'hosp-1',
      departmentOrAffiliation: 'Apollo Health City Operations',
      isActive: true,
      createdAt: '2026-01-10T08:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
    {
      id: 'usr-admin-sys-1',
      email: 'sysadmin.priya@demo.aegiscare.in',
      passwordHash: defaultPasswordHash.hash,
      salt: defaultPasswordHash.salt,
      role: 'system_admin',
      name: 'Priya Nambiar',
      title: 'Principal Security Officer',
      avatarInitials: 'PN',
      phone: '+91 98490 67890',
      departmentOrAffiliation: 'AegisCare Security & Platform Operations',
      isActive: true,
      createdAt: '2026-01-10T08:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
  ],

  patients: [
    {
      id: 'pat-1',
      userId: 'usr-patient-1',
      abhaId: '91-4582-7710-3342',
      name: 'Rajesh Sharma',
      age: 68,
      gender: 'Male',
      bloodGroup: 'O+',
      phone: '+91 98490 11223',
      emergencyContact: {
        name: 'Sneha Sharma (Daughter)',
        relationship: 'Daughter',
        phone: '+91 98490 33445',
      },
      address: 'Plot 42, Road No 10, Banjara Hills',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500034',
      createdAt: '2026-01-15T09:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
    {
      id: 'pat-2',
      userId: 'usr-family-1',
      abhaId: '91-8841-2390-1120',
      name: 'Lakshmi Devi',
      age: 74,
      gender: 'Female',
      bloodGroup: 'B+',
      phone: '+91 98490 88990',
      emergencyContact: {
        name: 'Sneha Sharma (Granddaughter)',
        relationship: 'Granddaughter',
        phone: '+91 98490 33445',
      },
      address: 'Apt 302, Green Meadows, Jubilee Hills',
      city: 'Hyderabad',
      state: 'Telangana',
      pincode: '500033',
      createdAt: '2026-02-01T09:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
  ],

  medicalProfiles: [
    {
      id: 'med-1',
      patientId: 'pat-1',
      bloodGroup: 'O+',
      allergies: ['Penicillin', 'Sulfa Drugs'],
      chronicConditions: ['Type 2 Diabetes Mellitus', 'Essential Hypertension', 'Coronary Artery Disease'],
      currentMedications: ['Metformin 500mg BD', 'Telmisartan 40mg OD', 'Aspirin 75mg OD', 'Atorvastatin 20mg HS'],
      pastSurgeries: ['Percutaneous Transluminal Coronary Angioplasty (2022)'],
      insuranceProvider: 'Star Health Senior Citizen Insurance',
      policyNumber: 'SH-IND-HYD-882109',
      primaryPhysicianName: 'Dr. Ananya Rao',
      primaryPhysicianHospital: 'Apollo Health City, Jubilee Hills',
      qrAccessCode: 'AEGIS-QR-HYD-PAT1-VERIFIED',
      createdAt: '2026-01-15T09:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
  ],

  emergencyCases: [
    {
      id: 'case-1',
      caseNumber: 'EMR-HYD-2026-0842',
      patientId: 'pat-1',
      patientName: 'Rajesh Sharma',
      patientAge: 68,
      patientGender: 'Male',
      chiefComplaint: 'Acute retrosternal chest pressure radiating to left arm with diaphoresis',
      severity: 'Critical',
      status: 'In Transit',
      reportedAt: '2026-09-17T08:14:00.000Z',
      pickupLocation: {
        address: 'Banjara Hills Road No 10, Near City Center Mall',
        landmark: 'Near City Center Mall',
        lat: 17.4156,
        lng: 78.4357,
      },
      assignedAmbulanceId: 'amb-1',
      assignedHospitalId: 'hosp-1',
      assignedEmtName: 'Vikram Singh, EMT-P',
      careCategoryRequired: 'Acute Coronary Syndrome (STEMI Code Blue)',
      notes: [
        'Caller reports onset 25 mins ago while ascending stairs',
        'Aspirin 325mg chewed and Nitroglycerin 0.4mg sublingual administered by EMT at 08:22',
        '12-Lead ECG transmitted showing ST Elevation in leads II, III, aVF',
      ],
      createdAt: '2026-09-17T08:14:00.000Z',
      updatedAt: '2026-09-17T08:26:00.000Z',
    },
  ],

  ambulances: [
    {
      id: 'amb-1',
      unitCode: '108-HYD-42',
      vehicleNumber: 'TS 09 UA 1084',
      type: 'ALS',
      status: 'In Transit',
      baseLocation: 'Banjara Hills Depot',
      currentGps: {
        address: 'En route to Apollo Health City via Road No 36',
        lat: 17.4239,
        lng: 78.4284,
      },
      assignedDriver: 'Mohammed Raheem',
      assignedEmtId: 'usr-emt-1',
      assignedEmtName: 'Vikram Singh, EMT-P',
      currentCaseId: 'case-1',
      destinationHospitalId: 'hosp-1',
      batteryPercentage: 94,
      oxygenReservePercentage: 88,
      etaMinutes: 6,
      greenCorridorActive: true,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-09-17T08:28:00.000Z',
    },
    {
      id: 'amb-2',
      unitCode: '108-HYD-18',
      vehicleNumber: 'TS 09 UA 1088',
      type: 'ALS',
      status: 'Available',
      baseLocation: 'Gachibowli Cyber Towers Depot',
      currentGps: {
        address: 'Hitech City Main Road, Cyber Towers Junction',
        lat: 17.4474,
        lng: 78.3762,
      },
      assignedDriver: 'G. Srinivas',
      assignedEmtId: 'usr-emt-2',
      assignedEmtName: 'Ramesh Babu, EMT-B',
      batteryPercentage: 98,
      oxygenReservePercentage: 95,
      etaMinutes: 0,
      greenCorridorActive: false,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
  ],

  vitalReadings: [
    {
      id: 'vit-1',
      caseId: 'case-1',
      ambulanceId: 'amb-1',
      patientId: 'pat-1',
      heartRate: 114,
      spO2: 96,
      bloodPressure: '148/92',
      respRate: 22,
      temperature: 98.6,
      bloodGlucose: 142,
      ecgStatus: 'Inferior ST Elevation (STEMI Alert)',
      recordedByEmtName: 'Vikram Singh, EMT-P',
      timestamp: '2026-09-17T08:25:30.000Z',
    },
  ],

  hospitals: [
    {
      id: 'hosp-1',
      name: 'Apollo Health City',
      address: 'Road No 72, Film Nagar, Jubilee Hills',
      area: 'Jubilee Hills',
      city: 'Hyderabad',
      traumaLevel: 'Level 1',
      totalBeds: 550,
      availableBeds: 34,
      totalIcuBeds: 120,
      availableIcuBeds: 6,
      cathLabActive: true,
      strokeTeamActive: true,
      emergencyDeskPhone: '+91 40 2360 7777',
      lat: 17.4265,
      lng: 78.4112,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
    {
      id: 'hosp-2',
      name: 'Continental Hospitals',
      address: 'Financial District, Nanakramguda, Gachibowli',
      area: 'Gachibowli',
      city: 'Hyderabad',
      traumaLevel: 'Level 1',
      totalBeds: 400,
      availableBeds: 28,
      totalIcuBeds: 90,
      availableIcuBeds: 8,
      cathLabActive: true,
      strokeTeamActive: true,
      emergencyDeskPhone: '+91 40 6700 0000',
      lat: 17.4144,
      lng: 78.3498,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
    {
      id: 'hosp-3',
      name: 'NIMS (Nizam’s Institute of Medical Sciences)',
      address: 'Punjagutta, Somajiguda',
      area: 'Punjagutta',
      city: 'Hyderabad',
      traumaLevel: 'Level 1',
      totalBeds: 1100,
      availableBeds: 45,
      totalIcuBeds: 180,
      availableIcuBeds: 4,
      cathLabActive: true,
      strokeTeamActive: true,
      emergencyDeskPhone: '+91 40 2348 9000',
      lat: 17.4228,
      lng: 78.4552,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
  ],

  hospitalResourcePreps: [
    {
      id: 'prep-1',
      hospitalId: 'hosp-1',
      caseId: 'case-1',
      assignedBay: 'Trauma Resuscitation Bay 1 (Code STEMI)',
      traumaTeamNotified: true,
      cathLabReserved: true,
      strokeTeamAlerted: false,
      bloodBankAlerted: true,
      prepStatus: 'Surgical Suite Prepared',
      notes: 'Cath Lab 2 cleared; Interventional Cardiologist Dr. Ananya Rao standing by with On-Call Fellow',
      updatedAt: '2026-09-17T08:26:00.000Z',
    },
  ],

  preArrivalNotifications: [
    {
      id: 'pan-1',
      caseId: 'case-1',
      ambulanceId: 'amb-1',
      hospitalId: 'hosp-1',
      senderName: 'Vikram Singh, EMT-P',
      senderRole: 'emt',
      message: 'ALS Unit 108-HYD-42 inbound with STEMI patient. 12-lead transmitted. ETA 6 minutes.',
      urgency: 'stat',
      timestamp: '2026-09-17T08:24:00.000Z',
    },
  ],

  doctors: [
    {
      id: 'doc-1',
      userId: 'usr-doctor-1',
      name: 'Dr. Ananya Rao, MD, DM (Cardiology)',
      specialty: 'Interventional Cardiology & Emergency Medicine',
      hospitalId: 'hosp-1',
      hospitalName: 'Apollo Health City, Jubilee Hills',
      registrationNumber: 'TSMC-64821-2015',
      qualifications: 'MBBS, MD (General Medicine), DM (Cardiology)',
      isAvailableForEmergency: true,
      activeConsultationsCount: 2,
      createdAt: '2026-01-01T00:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
  ],

  clinicalOrders: [
    {
      id: 'ord-1',
      caseId: 'case-1',
      doctorId: 'doc-1',
      doctorName: 'Dr. Ananya Rao, MD',
      orderText: 'Administer Aspirin 325mg PO + Clopidogrel 300mg Loading Dose + IV Access 18G',
      category: 'Medication',
      status: 'Administered',
      timestamp: '2026-09-17T08:22:00.000Z',
    },
    {
      id: 'ord-2',
      caseId: 'case-1',
      doctorId: 'doc-1',
      doctorName: 'Dr. Ananya Rao, MD',
      orderText: 'Prepare Heparin 5000 IU Bolus for Cath Lab Transfer upon arrival',
      category: 'Prep',
      status: 'Ordered',
      timestamp: '2026-09-17T08:27:00.000Z',
    },
  ],

  familyRelationships: [
    {
      id: 'rel-1',
      familyUserId: 'usr-family-1',
      familyMemberName: 'Sneha Sharma',
      patientId: 'pat-1',
      patientName: 'Rajesh Sharma',
      relationship: 'Child',
      isEmergencyContact: true,
      isAuthorizedCaregiver: true,
      createdAt: '2026-01-15T09:00:00.000Z',
      updatedAt: '2026-09-17T08:00:00.000Z',
    },
  ],

  consentRecords: [
    {
      id: 'con-1',
      patientId: 'pat-1',
      authorizedUserId: 'usr-family-1',
      authorizedUserName: 'Sneha Sharma',
      purpose: 'Caregiver Monitoring',
      status: 'Active',
      grantedAt: '2026-01-15T09:00:00.000Z',
      expiresAt: '2027-01-15T09:00:00.000Z',
      ipAddress: '192.168.1.42',
    },
    {
      id: 'con-2',
      patientId: 'pat-1',
      authorizedUserId: 'usr-emt-1',
      authorizedUserName: 'Vikram Singh, EMT-P',
      purpose: 'Emergency Response',
      status: 'Active',
      grantedAt: '2026-09-17T08:15:00.000Z',
      expiresAt: '2026-09-18T08:15:00.000Z',
      ipAddress: '10.8.42.1',
    },
  ],

  notifications: [
    {
      id: 'notif-1',
      userId: 'usr-patient-1',
      targetRole: 'patient',
      title: '108 Ambulance Dispatched',
      message: 'ALS Unit 108-HYD-42 is en route to your location. ETA ~6 minutes.',
      severity: 'urgent',
      read: false,
      createdAt: '2026-09-17T08:16:00.000Z',
    },
    {
      id: 'notif-2',
      userId: 'usr-doctor-1',
      targetRole: 'doctor',
      title: 'Incoming Inpatient Case #0842 (STEMI)',
      message: 'Lead Paramedic Vikram Singh transmitted 12-Lead ECG. Cath Lab Prep required.',
      severity: 'critical',
      read: false,
      createdAt: '2026-09-17T08:24:00.000Z',
    },
  ],

  auditEvents: [
    {
      id: 'aud-1',
      timestamp: '2026-09-17T08:14:02.000Z',
      actorId: 'usr-patient-1',
      actorRole: 'patient',
      actorName: 'Rajesh Sharma',
      actionType: 'LOGIN',
      resourceType: 'User',
      resourceId: 'usr-patient-1',
      reason: 'Authentication successful for Patient portal session',
      ipAddress: '127.0.0.1',
      status: 'SUCCESS',
    },
    {
      id: 'aud-2',
      timestamp: '2026-09-17T08:22:15.000Z',
      actorId: 'usr-doctor-1',
      actorRole: 'doctor',
      actorName: 'Dr. Ananya Rao, MD',
      actionType: 'ISSUE_ORDER',
      resourceType: 'ClinicalOrder',
      resourceId: 'ord-1',
      reason: 'Emergency pre-arrival pharmacotherapy instruction for ACS case #case-1',
      ipAddress: '10.0.4.15',
      status: 'SUCCESS',
    },
  ],
};
